language: c

os: linux
dist: xenial

services: docker

#Cache doxygen
cache:
  directories:
    - /home/travis/doxygen/doxygen-1.8.18/bin

before_install:
  # Travis has an OLD doxygen build, so we fetch a recent one
  - export DOXY_BINPATH=/home/travis/doxygen/doxygen-1.8.18/bin
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mkdir -p ~/doxygen && cd ~/doxygen; fi
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then wget http://doxygen.nl/files/doxygen-1.8.18.linux.bin.tar.gz; fi
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then tar xzf doxygen-1.8.18.linux.bin.tar.gz; fi
  - export PATH=$PATH:$DOXY_BINPATH

install:
  - docker pull devkitpro/devkitarm

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/libctru devkitpro/devkitarm /bin/bash -ex /libctru/.travis/docker.sh

before_deploy:
  - sh .travis/exportdoc.sh

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: libctru/docs/html
  on:
    tags: true
    branch: master
