language: c

os: linux
dist: xenial

services: docker

#Cache doxygen
cache:
  directories:
    - /home/travis/doxygen/doxygen-1.8.18/bin

before_install:
  # Travis has an OLD doxygen build, so we fetch a recent one
  - export DOXY_BINPATH=/home/travis/doxygen/doxygen-1.8.18/bin
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ -n "$TRAVIS_TAG" ]; then mkdir -p ~/doxygen && cd ~/doxygen; fi
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ -n "$TRAVIS_TAG" ]; then wget http://doxygen.nl/files/doxygen-1.8.18.linux.bin.tar.gz; fi
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ -n "$TRAVIS_TAG" ]; then tar xzf doxygen-1.8.18.linux.bin.tar.gz; fi
  - if [ -n "$TRAVIS_TAG" ]; then openssl aes-256-cbc -K $encrypted_1b844421d50b_key -iv $encrypted_1b844421d50b_iv -in .travis/id_travis_deploy.enc -out .travis/id_travis_deploy -d; fi
  - export PATH=$PATH:$DOXY_BINPATH

install:
  - docker pull devkitpro/devkitarm

script:
  - docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/libctru devkitpro/devkitarm /bin/bash -ex /libctru/.travis/docker.sh

before_deploy:
  - sh .travis/exportdoc.sh

deploy:
  provider: pages
  deploy_key: .travis/id_travis_deploy
  edge: true
  keep_history: false
  fqdn: libctru.devkitpro.org
  local_dir: libctru/docs/html
  on:
    tags: true
